version: '2'

services:
 
  # Add drupal contener.
  drupal:
    image: "ivoberz/drupal8-docker"
    container_name: "${PROJECT_NAME}-drupal"
    restart: always
    ports:
        - "8000:80" # web
        - "2222:22" # ssh
        - "35729:35729" # live reload
        - "9876:9876" # karma server
    volumes:
      - ./drupal:/var/www/html
      - ./.composer:/home/drupal/.composer # composer caching
      - ./.gitconfig:/home/drupal/.gitconfig # Git configuration ( access alias && config )
      - ./.ssh:/home/drupal/.ssh # Ssh keys for easy deployment inside the container
      - ./nginx/sites-available:/etc/nginx/sites-available # nginx sites ( in case you recreate the container )
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled # nginx sites ( in case you recreate the container )
    links:
      - mysql
  
  # Add MariaDB contener.
  mysql:
    image: mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;'
    container_name: "${PROJECT_NAME}-mariadb"
    restart: always
    volumes:
      - ./mariadb/date:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=drupal
    ports:
      - 3306:3306

  # Add Adminer contener.
  adminer:
    image: clue/adminer
    container_name: "${PROJECT_NAME}-adminer"
    ports:
      - 8081:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
    links:
      - mysql

  # Add PHPMyAdmin contener.
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}-phpmyadmin"
    links:
      - mysql
    ports:
      - 8082:80
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_HOST=mysql
